services:
  broker:
    image: eclipse-mosquitto
    restart: always
    network_mode: host
    ports:
      - 1883:1883
    volumes:
      - ./config:/mosquitto/config
      - ./logs:/mosquitto/log
      - ./data:/mosquitto/data

