#/etc/mosquito
version: '3.7'

services:
  broker:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes:
      - ./config:/mosquitto/config
      - ./logs:/mosquitto/log
      - ./data:/mosquitto/data
